print_planner:
  setpoint_rate:            30 #Hz

  #Take-off and landing
  tol_speed:                0.3 #m/s
  tol_height:               0.5 #m
        
  #TOPPRA     
  transition_vel:           0.20 #m/s
  transition_max_accel:     0.05 #m/s^2
  max_yawrate:              20 #deg/s
  max_yawrate_dot:          20 #deg/s^2

  #slicer 
  use_material_model:       false
  print_vel:                0.1 #m/s
  scan_height:              0.6 #m